fifth_app/urls.py
from django.urls import path
from fifth_app import views

# template urls
app_name = 'fifth_app'

urlpatterns = [
    path('login/', views.user_login, name='user_login'),
    path('logout/', views.user_logout, name='user_logout'),
    path('register/', views.register, name='register'),
]

fifth_project/urls.py
from django.contrib import admin
from django.urls import path, include
from fifth_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('fifth_app/', include('fifth_app.urls')),
]

fifth_app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class UserProfileInfo(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    # Additional classes
    portfolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to='fifth_app/profile_pics', blank=True)

    def __str__(self):
        return self.user.username

fifth_app/forms.py
from django import forms
from django.contrib.auth.models import User
from fifth_app.models import UserProfileInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password')

class UserProfileInfoForm(forms.ModelForm):
    class Meta:
        model = UserProfileInfo
        fields = ('portfolio_site', 'profile_pic')

fifth_app/views.py
from django.shortcuts import render
from fifth_app.forms import UserForm, UserProfileInfoForm

# Login functionality
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required

# Create your views here.
def index(request):
    return render(request, 'fifth_app/index.html')

def register(request):
    print(request.FILES)
    registered = False

    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save() # Hash the password before storing it in the db

            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user # Set the one to one field

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()

            registered = True
        else:
            print(user_form.errors, profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    return render(request, 'fifth_app/register.html', context={
        'registered': registered,
        'user_form': user_form,
        'profile_form': profile_form
    })

def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)
        
        if user:
            if user.is_active:
                login(request, user)
                
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse('Account not active')
        else:
            print('Failed authentication')

            return HttpResponse('Invalid login details supplied')
    else:
        return render(request, 'fifth_app/login.html')

@login_required
def user_logout(request):
    logout(request)
    
    return HttpResponseRedirect(reverse('index'))

templates/fifth_app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>{% block title %}{% endblock %}</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
</head>
<body>

  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="{% url 'index' %}">Django</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'admin:index' %}">Admin<span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'fifth_app:register' %}">Register</a>
        </li>

        {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'fifth_app:user_logout' %}">Logout</a>
          </li>
        {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'fifth_app:user_login' %}">Login</a>
          </li>
        {% endif %}

      </ul>
    </div>
  </nav>

  <div class="container">
    {% block body %}
    {% endblock %}
  </div>

  <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>


</html>

templates/fifth_app/index.html
<!-- Don't need to extend DOCTYPE because base.html automatically includes it on the top -->
{% extends "fifth_app/base.html" %}

<!-- Define the title -->
{% block title %}Index{% endblock %}

{% block body %}
  <div class="jumbotron">
    <h1>Django level five</h1>
  </div>
{% endblock %}

templates/fifth_app/login.html
{% extends 'fifth_app/base.html' %}

{% block title %}User login{% endblock %}

{% block body %}
 <div class="jumbotron">
   <h1>User login</h1>
   <form action="{% url 'fifth_app:user_login' %}" method="post">
     {% csrf_token %}
     
     <label for="user_login">Username:</label>
     <input type="text" name="username" placeholder="Enter username">

     <label for="password">Password:</label>
     <input type="password" name="password">
     
     <input type="submit" value="Login">
   </form>
 </div> 
{% endblock %}

templates/fifth_app/register.html
{% extends 'fifth_app/base.html' %}
{% load staticfiles %}

{% block body %}
<div class="jumbotron">
  {% if registered %}
  <h1>Thank you for registering</h1>
  {% else %}
  <h2>Register here</h2>

  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ user_form.as_p }}
    {{ profile_form.as_p }}

    <input type="submit" value="Register">
  </form>
  {% endif %}
</div>
{% endblock %}